@startuml test


class Person {
    - peselNUmber : String
    - name : String
    - lastname : String
    - gender : String
    - dateOfBirth : LocalDate
    ----
    + getName():String
    + setName(name: String):void
    + getLastname():String
    + setLastname(lastName: String):void
    + getPeselNumber():String
    + getGender():String
    + getDateOfBirth():LoocalDate

}

class PeselValidator {
    ----
    + {static}  isValid(pesel : String) : boolean
 }

@enduml